_target_: evals.datasets.nyu.NYU
train_path: /lustre/scratch/diff/datasets/nyu_geonet/data
test_path: /lustre/scratch/diff/datasets/nyuv2/nyuv2_snorm_all.pkl
image_mean: None
augment_train: True
center_crop: True
